/* Generated By:JavaCC: Do not edit this line. Compilador.java */
import java.io.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Stack;

public class Compilador implements CompiladorConstants {

    private ErrorHandler errorHandler;
    private TabelaDeSimbolos tabelaDeSimbolos = new TabelaDeSimbolos();
    private GeradorDeCodigo geradorDeCodigo = new GeradorDeCodigo();

    private int VP;
    private List<String> listaDeIdentificadoresDaLinha;
    private List<Integer> listaBasesDaLinha;
    private int categoriaAtual;
    private Stack<Integer> pilhaDeDesvios = new Stack<Integer>();
    private int baseDoUltimoVetor;
    private int tamanhoDoUltimoVetor;
    private boolean houveInitLinha;
    private int primeiroBaseInit;
    private int indiceCorrenteVetor;
    private Token indiceConstante = null;

    public Compilador(Reader stream, ErrorHandler handler) {
        this(stream);
        this.errorHandler = handler;
        this.tabelaDeSimbolos.setErrorHandler(handler); // Conecta o ErrorHandler
    }

    public String getCodigoGerado() {
        if (errorHandler.hasErrors()) {
            return "--- ERROS ENCONTRADOS. C\u00d3DIGO N\u00c3O GERADO ---";
        }
        return geradorDeCodigo.getCodigoIntermediario();
    }

    public static void main(String args[]) throws TokenMgrError, FileNotFoundException, ParseException {
        try {
            if (args.length == 0) {
                System.err.println("Uso: java Compilador <arquivo-fonte>");
                return;
            }
            ErrorHandler consoleHandler = new ErrorHandler();
            Reader reader = new InputStreamReader(new FileInputStream(args[0]));
            Compilador parser = new Compilador(reader, consoleHandler);
            System.out.println("=== Iniciando an\u00e1lise l\u00e9xica e sint\u00e1tica ===");

            parser.programa();

            if (consoleHandler.hasErrors()) {
                System.out.println("\n=== Erros encontrados: ===");
                for (String error : consoleHandler.getErrorMessages()) {
                    System.err.println("- " + error);
                }
            } else {
                System.out.println("\n=== An\u00e1lise conclu\u00edda com sucesso ===");
                System.out.println(parser.getCodigoGerado());
            }
        } catch (FileNotFoundException e) {
            System.err.println("Arquivo n\u00e3o encontrado: " + e.getMessage());
        } catch (TokenMgrError e) {
            System.err.println("ERRO L\u00c9XICO FATAL: " + e.getMessage());
        }
    }

// --- PRODUÇÕES SINTÁTICAS (GLC ANOTADA + MODO PÂNICO) ---
  final public void programa() throws ParseException {
    jj_consume_token(BEGIN);
    identificador_de_programa();
    declaracao();
    jj_consume_token(START);
    lista_de_comandos();
      geradorDeCodigo.gerar("STP", "0");
    jj_consume_token(END);
    jj_consume_token(DOT);
  }

  final public void identificador_de_programa() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      t = jj_consume_token(IDENTIFIER);
        tabelaDeSimbolos.inserirPrograma(t.image);
      break;
    default:
      jj_la1[0] = jj_gen;

    }
  }

  final public void declaracao() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case DEFINE:
      jj_consume_token(DEFINE);
          listaDeIdentificadoresDaLinha = new ArrayList<String>();
          listaBasesDaLinha = new ArrayList<Integer>();
          VP = 0;
          houveInitLinha = false;
          primeiroBaseInit = -1;
      lista_de_declaracao();
      break;
    default:
      jj_la1[1] = jj_gen;

    }
  }

  final public void lista_de_declaracao() throws ParseException {
    label_1:
    while (true) {
      declaracao_de_variaveis();
      lista_de_declaracao_linha();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case IDENTIFIER:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_1;
      }
    }
  }

  final public void lista_de_declaracao_linha() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      declaracao_de_variaveis();
      lista_de_declaracao_linha();
      break;
    default:
      jj_la1[3] = jj_gen;

    }
  }

// --- REGRA COM RECUPERAÇÃO DE ERRO ---
  final public void declaracao_de_variaveis() throws ParseException {
    try {
      lista_de_identificadores();
      jj_consume_token(COLON);
      tipo();
      decl_do_vetor();
      jj_consume_token(SEMICOLON);
            String op;
            if (categoriaAtual == 1) op = "ALI";
            else if (categoriaAtual == 2) op = "ALR";
            else if (categoriaAtual == 3) op = "ALS";
            else op = "ALB";
            if (VP > 0) {
                geradorDeCodigo.gerar(op, String.valueOf(VP));
            }

            if (houveInitLinha) {
                for (int k = 1; k < listaBasesDaLinha.size(); k++) {
                    geradorDeCodigo.gerar("LDV", String.valueOf(primeiroBaseInit));
                    geradorDeCodigo.gerar("STR", String.valueOf(listaBasesDaLinha.get(k)));
                }
            }

            listaDeIdentificadoresDaLinha.clear();
            listaBasesDaLinha.clear();
            VP = 0;
            houveInitLinha = false;
            primeiroBaseInit = -1;
    } catch (ParseException e) {
        // --- MODO PÂNICO ---
        if (errorHandler != null) {
            errorHandler.processParseException(e, "em declara\u00e7\u00e3o de vari\u00e1veis");
        }
        // Pula até um ';' ou o início de 'start'
        Token t;
        while (true) {
            t = getToken(1);
            if (t.kind == EOF || t.kind == START || t.kind == SEMICOLON) {
                if (t.kind == SEMICOLON) getNextToken(); // Consome o ';'
                break;
            }
            getNextToken();
        }
    }
  }

  final public void lista_de_identificadores() throws ParseException {
  Token t;
    t = jj_consume_token(IDENTIFIER);
        if (tabelaDeSimbolos.buscar(t.image) != null) {
            errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador '" + t.image + "' j\u00e1 declarado.");
        } else {
            listaDeIdentificadoresDaLinha.add(t.image);
        }
    lista_de_identificadores_linha();
  }

  final public void lista_de_identificadores_linha() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      t = jj_consume_token(IDENTIFIER);
            if (tabelaDeSimbolos.buscar(t.image) != null) {
                errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador '" + t.image + "' j\u00e1 declarado.");
            } else {
                listaDeIdentificadoresDaLinha.add(t.image);
            }
      lista_de_identificadores_linha();
      break;
    default:
      jj_la1[4] = jj_gen;

    }
  }

  final public void tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NUM:
      jj_consume_token(NUM);
              categoriaAtual = 1;
      break;
    case REAL:
      jj_consume_token(REAL);
               categoriaAtual = 2;
      break;
    case TEXT:
      jj_consume_token(TEXT);
               categoriaAtual = 3;
      break;
    case FLAG:
      jj_consume_token(FLAG);
               categoriaAtual = 4;
      break;
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void decl_do_vetor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      jj_consume_token(LBRACKET);
      constante_inteira();
      jj_consume_token(RBRACKET);
            // #V2
            int vtAtual = tabelaDeSimbolos.getVT();
            baseDoUltimoVetor = -1;
            for (String id : listaDeIdentificadoresDaLinha) {
                Simbolo s = tabelaDeSimbolos.inserir(id, categoriaAtual, tamanhoDoUltimoVetor);
                if (s != null) {
                    listaBasesDaLinha.add(s.getBase());
                    baseDoUltimoVetor = s.getBase();
                }
            }
            VP = (tamanhoDoUltimoVetor * listaDeIdentificadoresDaLinha.size());
      inic_vetor();
      break;
    default:
      jj_la1[7] = jj_gen;
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ASSIGN:
        jj_consume_token(ASSIGN);
        valor();
                             houveInitLinha = true;
        break;
      default:
        jj_la1[6] = jj_gen;

      }
            // #E2
            for (String id : listaDeIdentificadoresDaLinha) {
                Simbolo s = tabelaDeSimbolos.inserir(id, categoriaAtual, -1);
                if (s != null) {
                    listaBasesDaLinha.add(s.getBase());
                }
            }
            VP = listaDeIdentificadoresDaLinha.size();
            if (houveInitLinha) {
                // #IE
                primeiroBaseInit = listaBasesDaLinha.get(0);
                geradorDeCodigo.gerar("STR", String.valueOf(primeiroBaseInit));
            }
    }
  }

  final public void constante_inteira() throws ParseException {
  Token t;
    t = jj_consume_token(CONST_INT);
        // #V1
        int valor = Integer.parseInt(t.image);
        if (valor <= 0) {
            errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Tamanho do vetor deve ser maior que 0.");
            tamanhoDoUltimoVetor = 1;
        } else {
            tamanhoDoUltimoVetor = valor;
        }
  }

  final public void inic_vetor() throws ParseException {
  indiceCorrenteVetor = 0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ASSIGN:
      jj_consume_token(ASSIGN);
      jj_consume_token(LBRACE);
      lista_valores_vetor();
      jj_consume_token(RBRACE);
            if (indiceCorrenteVetor == 1) {
                int baseV = baseDoUltimoVetor;
                geradorDeCodigo.gerar("STR", String.valueOf(baseV));
                for (int j = 2; j <= tamanhoDoUltimoVetor; j++) {
                    geradorDeCodigo.gerar("LDV", String.valueOf(baseV));
                    geradorDeCodigo.gerar("STR", String.valueOf(baseV + (j-1)));
                }
            }
      break;
    default:
      jj_la1[8] = jj_gen;

    }
  }

  final public void lista_valores_vetor() throws ParseException {
    valor();
        // #VAL
        geradorDeCodigo.gerar("STR", String.valueOf(baseDoUltimoVetor + indiceCorrenteVetor));
        indiceCorrenteVetor++;
    lista_valores_vetor_linha();
  }

  final public void lista_valores_vetor_linha() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      valor();
            // #VAL
            geradorDeCodigo.gerar("STR", String.valueOf(baseDoUltimoVetor + indiceCorrenteVetor));
            indiceCorrenteVetor++;
      lista_valores_vetor_linha();
      break;
    default:
      jj_la1[9] = jj_gen;

    }
  }

  final public void valor() throws ParseException {
  Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case CONST_INT:
      t = jj_consume_token(CONST_INT);
                          geradorDeCodigo.gerar("LDI", t.image);
      break;
    case CONST_REAL:
      t = jj_consume_token(CONST_REAL);
                          geradorDeCodigo.gerar("LDR", t.image);
      break;
    case CONST_LITERAL:
      t = jj_consume_token(CONST_LITERAL);
                            geradorDeCodigo.gerar("LDS", t.image);
      break;
    case TRUE:
      t = jj_consume_token(TRUE);
                          geradorDeCodigo.gerar("LDB", "1");
      break;
    case FALSE:
      t = jj_consume_token(FALSE);
                          geradorDeCodigo.gerar("LDB", "0");
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// --- COMANDOS ---
  final public void lista_de_comandos() throws ParseException {
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SET:
      case READ:
      case SHOW:
      case IF:
      case LOOP:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_2;
      }
      try {
        comando();
      } catch (ParseException e) {
            // --- MODO PÂNICO (para comandos) ---
            if (errorHandler != null) {
                 errorHandler.processParseException(e, "em comando");
            }
            Token t;
            while (true) {
                t = getToken(1);
                if (t.kind == EOF || t.kind == END ||
                    t.kind == SET || t.kind == READ ||
                    t.kind == SHOW || t.kind == IF || t.kind == LOOP)
                {
                    break; // Ponto seguro
                }
                getNextToken();
            }
      }
    }
  }

  final public void comando() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SET:
      atribuicao();
      break;
    case READ:
      entrada();
      break;
    case SHOW:
      saida();
      break;
    case IF:
      selecao();
      break;
    case LOOP:
      repeticao();
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void atribuicao() throws ParseException {
    Token t;
    Simbolo simboloLHS;
    boolean temIndiceLHS = false;
    try {
      jj_consume_token(SET);
      t = jj_consume_token(IDENTIFIER);
            simboloLHS = tabelaDeSimbolos.buscar(t.image);
            if (simboloLHS == null) {
                errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador '" + t.image + "' n\u00e3o declarado.");
            }
            this.indiceConstante = null; // Reseta a memória

          temIndiceLHS = indice_atribuicao(simboloLHS);
      jj_consume_token(ASSIGN);
      expressao();
            if (simboloLHS != null) {
                if (simboloLHS.isVetor() && !temIndiceLHS) {
                    errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador de vetor '" + simboloLHS.getLexema() + "' deve ser indexado.");
                } else if (!simboloLHS.isVetor() && temIndiceLHS) {
                    errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador escalar '" + simboloLHS.getLexema() + "' n\u00e3o pode ser indexado.");
                }
            }
            if (simboloLHS != null) {
                if (temIndiceLHS) {
                    if (this.indiceConstante != null) {
                        // --- OTIMIZAÇÃO (Programa A) ---
                        // O VALOR (42) está no topo da pilha
                        int indice = Integer.parseInt(this.indiceConstante.image);
                        int endereco = simboloLHS.getBase() + (indice - 1);
                        geradorDeCodigo.gerar("STR", String.valueOf(endereco)); // Usa STR direto
                    } else {
                        // --- ACESSO INDIRETO (Programa B) ---
                        // O VALOR (99) está no topo da pilha.
                        // A expressão do índice NÃO gerou código. Temos que gerar agora.
                        // (Esta parte falta no seu .jj original)

                        // Recriar a lógica de 'indice_atribuicao' aqui:
                        // Gerar código para o índice (que já foi parseado)
                        // A sua gramática não permite isso facilmente.

                        // **** SOLUÇÃO MAIS SIMPLES ****
                        // Reverta a `indice_atribuicao` para gerar código,
                        // e adicione `SWP` (Swap) aqui.

                        // Por favor, reverta as mudanças 1 e 2.
                        // Mantenha apenas a mudança da variável 'indiceConstante'.
                        // E use esta lógica em #A3:

                        // (Após reverter 1 e 2, a Pilha está:
                        // [ENDEREÇO (subtopo), VALOR (topo)]

                        geradorDeCodigo.gerar("SWP", "0"); // Inverte a pilha
                        geradorDeCodigo.gerar("STX", "0"); // Agora está correto
                    }
                } else {
                    // --- ESCALAR ---
                    geradorDeCodigo.gerar("STR", String.valueOf(simboloLHS.getBase()));
                }
            }
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {

    }
  }

  final public boolean indice_atribuicao(Simbolo simboloLHS) throws ParseException {
  Token tok = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      jj_consume_token(LBRACKET);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case CONST_INT:
        // Ramo 1: Otimização (é uma constante)
                    tok = jj_consume_token(CONST_INT);
                this.indiceConstante = tok; // Salva o token da constante

        break;
      case TRUE:
      case FALSE:
      case CONST_REAL:
      case CONST_LITERAL:
      case IDENTIFIER:
      case OP_LOGIC_NOT:
      case LPAREN:
        expressao();
                this.indiceConstante = null; // Marca como não-constante

        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(RBRACKET);
          {if (true) return true;}
      break;
    default:
      jj_la1[14] = jj_gen;

             this.indiceConstante = null; {if (true) return false;}
    }
    throw new Error("Missing return statement in function");
  }

// ENTRADA
  final public void entrada() throws ParseException {
    Token t;
    Simbolo simboloLHS;
    boolean temIndiceLHS = false;
    try {
      jj_consume_token(READ);
      jj_consume_token(LPAREN);
      t = jj_consume_token(IDENTIFIER);
            simboloLHS = tabelaDeSimbolos.buscar(t.image);
            if (simboloLHS == null) {
                errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador '" + t.image + "' n\u00e3o declarado.");
            }
          temIndiceLHS = indice_entrada(simboloLHS);
            if (simboloLHS != null) {
                if (simboloLHS.isVetor() && !temIndiceLHS) {
                    errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador de vetor '" + simboloLHS.getLexema() + "' deve ser indexado.");
                } else if (!simboloLHS.isVetor() && temIndiceLHS) {
                    errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador escalar '" + simboloLHS.getLexema() + "' n\u00e3o pode ser indexado.");
                }

                geradorDeCodigo.gerar("REA", String.valueOf(simboloLHS.getCategoria()));

                if (temIndiceLHS) {
                    geradorDeCodigo.gerar("STX", "0");
                } else {
                    geradorDeCodigo.gerar("STR", String.valueOf(simboloLHS.getBase()));
                }
            }
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if (errorHandler != null) {
             errorHandler.processParseException(e, "em comando 'read'");
        }
        while (true) {
            t = getToken(1);
            if (t.kind == EOF || t.kind == SEMICOLON) {
                 if (t.kind == SEMICOLON) getNextToken();
                 break;
            }
            getNextToken();
        }
    }
  }

  final public boolean indice_entrada(Simbolo simboloLHS) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      jj_consume_token(LBRACKET);
      expressao();
            if(simboloLHS != null) {
                geradorDeCodigo.gerar("LDI", String.valueOf(simboloLHS.getBase() - 1));
                geradorDeCodigo.gerar("ADD", "0");
            }
      jj_consume_token(RBRACKET);
          {if (true) return true;}
      break;
    default:
      jj_la1[15] = jj_gen;

             {if (true) return false;}
    }
    throw new Error("Missing return statement in function");
  }

// SAÍDA
  final public void saida() throws ParseException {
    try {
      jj_consume_token(SHOW);
      jj_consume_token(LPAREN);
      lista_de_saida();
      jj_consume_token(RPAREN);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if (errorHandler != null) {
             errorHandler.processParseException(e, "em comando 'show'");
        }
        Token t;
        while (true) {
            t = getToken(1);
            if (t.kind == EOF || t.kind == SEMICOLON) {
                 if (t.kind == SEMICOLON) getNextToken();
                 break;
            }
            getNextToken();
        }
    }
  }

  final public void lista_de_saida() throws ParseException {
    item();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_3;
      }
      jj_consume_token(COMMA);
      item();
    }
  }

  final public void item() throws ParseException {
    elemento();
                     geradorDeCodigo.gerar("WRT", "0");
  }

// SELEÇÃO
  final public void selecao() throws ParseException {
  int desvioJMF, desvioJMP;
    try {
      jj_consume_token(IF);
      expressao();
            desvioJMF = geradorDeCodigo.gerar("JMF", "0");
            pilhaDeDesvios.push(desvioJMF);
      jj_consume_token(THEN);
      lista_de_comandos();
      senao();
            int enderecoPendente = pilhaDeDesvios.pop();
            geradorDeCodigo.corrigir(enderecoPendente, String.valueOf(geradorDeCodigo.getProximoPonteiro()));
      jj_consume_token(END);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if (errorHandler != null) {
             errorHandler.processParseException(e, "em comando 'if'");
        }
        // Recuperação: Pula até o ';'
        Token t;
        while (true) {
            t = getToken(1);
            if (t.kind == EOF || t.kind == SEMICOLON) {
                 if (t.kind == SEMICOLON) getNextToken();
                 break;
            }
            getNextToken();
        }
    }
  }

  final public void senao() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case ELSE:
      jj_consume_token(ELSE);
            int desvioJMF = pilhaDeDesvios.pop();
            int desvioJMP = geradorDeCodigo.gerar("JMP", "0");
            geradorDeCodigo.corrigir(desvioJMF, String.valueOf(geradorDeCodigo.getProximoPonteiro()));
            pilhaDeDesvios.push(desvioJMP);
      lista_de_comandos();
      break;
    default:
      jj_la1[17] = jj_gen;

    }
  }

// REPETIÇÃO
  final public void repeticao() throws ParseException {
  int inicioLoop, desvioJMF;
    try {
      jj_consume_token(LOOP);
      jj_consume_token(WHILE);
          inicioLoop = geradorDeCodigo.getProximoPonteiro();
      expressao();
            desvioJMF = geradorDeCodigo.gerar("JMF", "0");
            pilhaDeDesvios.push(desvioJMF);
      lista_de_comandos();
            geradorDeCodigo.gerar("JMP", String.valueOf(inicioLoop));
            int enderecoJMF = pilhaDeDesvios.pop();
            geradorDeCodigo.corrigir(enderecoJMF, String.valueOf(geradorDeCodigo.getProximoPonteiro()));
      jj_consume_token(END);
      jj_consume_token(SEMICOLON);
    } catch (ParseException e) {
        if (errorHandler != null) {
             errorHandler.processParseException(e, "em comando 'loop'");
        }
        // Recuperação: Pula até o ';'
        Token t;
        while (true) {
            t = getToken(1);
            if (t.kind == EOF || t.kind == SEMICOLON) {
                 if (t.kind == SEMICOLON) getNextToken();
                 break;
            }
            getNextToken();
        }
    }
  }

// --- EXPRESSÃO ---
  final public void expressao() throws ParseException {
    expressao_aritmetica_ou_logica();
    expressao_linha();
  }

  final public void expressao_linha() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP_REL_EQ:
      jj_consume_token(OP_REL_EQ);
      expressao_aritmetica_ou_logica();
                                                     geradorDeCodigo.gerar("EQL", "0");
      break;
    case OP_REL_NEQ:
      jj_consume_token(OP_REL_NEQ);
      expressao_aritmetica_ou_logica();
                                                      geradorDeCodigo.gerar("DIF", "0");
      break;
    case OP_REL_LTLT:
      jj_consume_token(OP_REL_LTLT);
      expressao_aritmetica_ou_logica();
                                                       geradorDeCodigo.gerar("SMR", "0");
      break;
    case OP_REL_GTGT:
      jj_consume_token(OP_REL_GTGT);
      expressao_aritmetica_ou_logica();
                                                       geradorDeCodigo.gerar("BGR", "0");
      break;
    case OP_REL_LTLT_EQ:
      jj_consume_token(OP_REL_LTLT_EQ);
      expressao_aritmetica_ou_logica();
                                                          geradorDeCodigo.gerar("SME", "0");
      break;
    case OP_REL_GTGT_EQ:
      jj_consume_token(OP_REL_GTGT_EQ);
      expressao_aritmetica_ou_logica();
                                                          geradorDeCodigo.gerar("BGE", "0");
      break;
    default:
      jj_la1[18] = jj_gen;

    }
  }

  final public void expressao_aritmetica_ou_logica() throws ParseException {
    termo2();
    menor_prioridade();
  }

  final public void menor_prioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP_ARIT_SUM:
      jj_consume_token(OP_ARIT_SUM);
      termo2();
                               geradorDeCodigo.gerar("ADD", "0");
      menor_prioridade();
      break;
    case OP_ARIT_SUB:
      jj_consume_token(OP_ARIT_SUB);
      termo2();
                               geradorDeCodigo.gerar("SUB", "0");
      menor_prioridade();
      break;
    case OP_LOGIC_OR:
      jj_consume_token(OP_LOGIC_OR);
      termo2();
                               geradorDeCodigo.gerar("OR", "0");
      menor_prioridade();
      break;
    default:
      jj_la1[19] = jj_gen;

    }
  }

  final public void termo2() throws ParseException {
    termo1();
    media_prioridade();
  }

  final public void media_prioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP_ARIT_MUL:
      jj_consume_token(OP_ARIT_MUL);
      termo1();
                               geradorDeCodigo.gerar("MUL", "0");
      media_prioridade();
      break;
    case OP_ARIT_DIV:
      jj_consume_token(OP_ARIT_DIV);
      termo1();
                               geradorDeCodigo.gerar("DIV", "0");
      media_prioridade();
      break;
    case OP_ARIT_MOD:
      jj_consume_token(OP_ARIT_MOD);
      termo1();
                               geradorDeCodigo.gerar("MOD", "0");
      media_prioridade();
      break;
    case OP_ARIT_DIVINT:
      jj_consume_token(OP_ARIT_DIVINT);
      termo1();
                                  geradorDeCodigo.gerar("REM", "0");
      media_prioridade();
      break;
    case OP_LOGIC_AND:
      jj_consume_token(OP_LOGIC_AND);
      termo1();
                                geradorDeCodigo.gerar("AND", "0");
      media_prioridade();
      break;
    default:
      jj_la1[20] = jj_gen;

    }
  }

  final public void termo1() throws ParseException {
    elemento();
    maior_prioridade();
  }

  final public void maior_prioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP_ARIT_POW:
      jj_consume_token(OP_ARIT_POW);
      elemento();
                                 geradorDeCodigo.gerar("POW", "0");
      maior_prioridade();
      break;
    default:
      jj_la1[21] = jj_gen;

    }
  }

// --- SUBSTITUA A REGRA "elemento()" INTEIRA POR ISTO ---
  final public void elemento() throws ParseException {
    Token t;
    Simbolo simboloRHS;
    boolean temIndiceRHS = false;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case IDENTIFIER:
      // --- RAMO 1: IDENTIFICADOR (com a nova lógica) ---
              t = jj_consume_token(IDENTIFIER);
            simboloRHS = tabelaDeSimbolos.buscar(t.image);
            if (simboloRHS == null) {
                errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador '" + t.image + "' n\u00e3o declarado.");
            }
            this.indiceConstante = null; // Reseta a memória

          temIndiceRHS = indice_expressao(simboloRHS);
          // #E2 (Geração de Código)
            if (simboloRHS != null) {
                // Validação Semântica
                if (simboloRHS.isVetor() && !temIndiceRHS) {
                    errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador de vetor '" + simboloRHS.getLexema() + "' deve ser indexado.");
                } else if (!simboloRHS.isVetor() && temIndiceRHS) {
                    errorHandler.addError("Sem\u00e2ntico", t.beginLine, t.beginColumn, "Identificador escalar '" + simboloRHS.getLexema() + "' n\u00e3o pode ser indexado.");
                }

                // Geração de Código
                if (temIndiceRHS) {
                    if (this.indiceConstante != null) {
                        // O índice foi constante. Calculamos o endereço final.
                        int indice = Integer.parseInt(this.indiceConstante.image);
                        int endereco = simboloRHS.getBase() + (indice - 1);
                        geradorDeCodigo.gerar("LDV", String.valueOf(endereco));
                    } else {
                        // --- ACESSO INDIRETO (Programa B) ---
                        // O índice era uma expressão.
                        // A regra 'indice_expressao' já gerou o código do ENDEREÇO.
                        // A pilha está pronta para o LDX.
                        geradorDeCodigo.gerar("LDX", "0");
                    }
                } else {
                    // --- ESCALAR ---
                    geradorDeCodigo.gerar("LDV", String.valueOf(simboloRHS.getBase()));
                }
            }
      break;
    case CONST_INT:
      // --- RAMO 2: CONST_INT ---
              t = jj_consume_token(CONST_INT);
                            geradorDeCodigo.gerar("LDI", t.image);
      break;
    case CONST_REAL:
      // --- RAMO 3: CONST_REAL ---
              t = jj_consume_token(CONST_REAL);
                            geradorDeCodigo.gerar("LDR", t.image);
      break;
    case CONST_LITERAL:
      // --- RAMO 4: CONST_LITERAL ---
              t = jj_consume_token(CONST_LITERAL);
                              geradorDeCodigo.gerar("LDS", t.image);
      break;
    case TRUE:
      // --- RAMO 5: TRUE ---
              t = jj_consume_token(TRUE);
                            geradorDeCodigo.gerar("LDB", "1");
      break;
    case FALSE:
      // --- RAMO 6: FALSE ---
              t = jj_consume_token(FALSE);
                            geradorDeCodigo.gerar("LDB", "0");
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
      expressao();
      jj_consume_token(RPAREN);
      break;
    case OP_LOGIC_NOT:
      jj_consume_token(OP_LOGIC_NOT);
      jj_consume_token(LPAREN);
      expressao();
      jj_consume_token(RPAREN);
          geradorDeCodigo.gerar("NOT", "0");
      break;
    default:
      jj_la1[22] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public boolean indice_expressao(Simbolo simboloRHS) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LBRACKET:
      jj_consume_token(LBRACKET);
      expressao();
            if(simboloRHS != null) {
                geradorDeCodigo.gerar("LDI", String.valueOf(simboloRHS.getBase() - 1));
                geradorDeCodigo.gerar("ADD", "0");
            }
      jj_consume_token(RBRACKET);
          {if (true) return true;}
      break;
    default:
      jj_la1[23] = jj_gen;

             {if (true) return false;}
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public CompiladorTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[24];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
      jj_la1_init_2();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x10000000,0x100,0x10000000,0x10000000,0x0,0x780000,0x0,0x0,0x0,0x0,0xf800000,0x27800,0x27800,0x1f800000,0x0,0x0,0x0,0x10000,0x80000000,0x0,0x0,0x0,0x1f800000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x0,0x0,0x0,0x20000,0x0,0x8000,0x100000,0x8000,0x20000,0x0,0x0,0x0,0x44000,0x100000,0x100000,0x20000,0x0,0x1f,0x2180,0x1e40,0x20,0x44000,0x100000,};
   }
   private static void jj_la1_init_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }

  /** Constructor with InputStream. */
  public Compilador(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Compilador(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Compilador(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new CompiladorTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Compilador(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(CompiladorTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 24; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List jj_expentries = new java.util.ArrayList();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[66];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 24; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 66; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
